name: ParaCDCL CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15.0'
        ocaml_version: ['4.13.1']

    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
          with:
            coq_version: ${{ matrix.coq_version }}
            ocaml_version: ${{ matrix.ocaml_version }}
      - run: bash ./test.sh